name: 'WP Build Deploy'
author: Sultan Nasir Uddin
description: 'Build WordPress Theme and Plugin from GitHub Actions'
branding:
  icon: 'upload-cloud'
  color: 'blue'
inputs:
  php_version:
    description: 'PHP version to use'
    required: false
    default: '7.1'
  assets_build:
    required: false
    description: 'Build assets?'
  composer_build:
    required: false
    description: 'Build composer?'
  generate_zip:
    required: false
    description: 'Generate package zip file?'
  zip_name:
    required: false
    description: 'Name of the zip file?'
  wp_deploy:
    required: false
    description: 'Should we deploy to WP?'
  wp_url:
    required: false
    description: 'WP URL'
    default: 'https://plugins.svn.wordpress.org'
  wp_slug:
    required: false
    description: 'WP slug'
  wp_username:
    required: false
    description: 'WP username'
  wp_password:
    required: false
    description: 'WP password'
  dry_run:
    required: false
    description: 'Deploy dryrun?'
    default: 'false'
  version:
    required: false
    description: 'Version'
  assets_dir:
    required: false
    description: 'Assets directory'
    default: '.wordpress-org'
outputs:
  zip_path:
    description: 'Zip file path'
    value: ${{ steps.deploy.outputs.zip_path }}
  zip_name:
    description: 'Zip file name'
    value: ${{ steps.deploy.outputs.zip_name }}
  version:
    description: 'Release version'
    value: ${{ steps.deploy.outputs.version }}
runs:
  using: 'composite'
  steps:
    - name: Setup Environment
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.php_version }}
        coverage: none
        tools: composer

    - name: Tool versions
      shell: bash
      run: |
        php --version
        composer --version
        node --version

    - id: deploy
      run: ${{ github.action_path }}/run.sh
      env:
        ASSETS_BUILD: ${{ inputs.assets_build }}
        COMPOSER_BUILD: ${{ inputs.composer_build }}
        GENERATE_ZIP: ${{ inputs.generate_zip }}
        ZIP_NAME: ${{ inputs.zip_name }}
        WP_DEPLOY: ${{ inputs.wp_deploy }}
        DRY_RUN: ${{ inputs.dry_run }}
        WP_SLUG: ${{ inputs.wp_slug }}
        WP_USERNAME: ${{ inputs.wp_username }}
        WP_PASSWORD: ${{ inputs.wp_password }}
        VERSION: ${{ inputs.version }}
        ASSETS_DIR: ${{ inputs.assets_dir }}
      shell: bash
#
#    - run: env
#      shell: bash

